config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root :to => "home#index" 
    
  resources :music_albums do
    resources :songs
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music_album.rb
require 'elasticsearch/model'

class MusicAlbum < ApplicationRecord
  
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  mount_uploader :photo, AvatarUploader
  has_many :songs
  belongs_to :user
  
  validates :name, presence: true
  
  after_save :refresh_elasticsearch_index
  
  def refresh_elasticsearch_index
    self.__elasticsearch__.index_document refresh: true
  end
  
end

app/models/song.rb
class Song < ApplicationRecord
  
  mount_uploader :song_attachment, AttachmentUploader
  has_one :music_album, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :albums
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @albums = params[:search_value].blank? ? MusicAlbum.all : MusicAlbum.search(params[:search_value]).records
  end
  
end

app/controllers/music_albums_controller.rb
class MusicAlbumsController < ApplicationController
  layout 'home'
  
  before_action :authenticate_user!
  before_action :find_album, only: [:edit, :update, :destroy]
  
  def index
    @albums = MusicAlbum.all
  end
  
  def new
    @album = MusicAlbum.new
  end
  
  def create
    @album = MusicAlbum.new(album_params.merge(:user_id => current_user.id))
    if @album.save
      flash[:notice] = "Successfully Created Album"
      redirect_to new_music_album_song_url(music_album_id: @album.id)
    else
      flash[:error] = @album.errors.full_messages.uniq.join(', ')
      render :new 
    end
  end
  
  def edit
  end
  
  def update
    updated_album = @album.update_attributes(album_params)
    flash[:notice] = "Successfully Updated Album" if updated_album
    flash[:error] = @album.errors.full_messages.uniq.join(', ') if !updated_album
    redirect_to music_album_songs_path(music_album_id: @album.id)
  end
  
  def destroy
    destroy_album = @album.delete
    flash.now[:notice] = "Successfully Deleted Album" if destroy_album
    flash.now[:error] = @album.errors.full_messages.uniq.join(', ') if !destroy_album
    redirect_to root_path
  end
  
  private
  
  def album_params
    params.require(:music_album).permit(:name, :photo, :genres, :artist, :user_id)
  end
  
  def find_album
    @album = MusicAlbum.find_by_id(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  layout 'home'
  
  before_action :authenticate_user!, except: [:index]
  
  before_action :find_album, only: [:index, :new, :create, :edit, :update, :destroy, :show]
  before_action :find_songs, only: [:edit, :update, :destroy]
  
  
  def index
    @songs = @album.songs.nil? ? [] : @album.songs
  end
  
  def new
    @song = Song.new
  end
  
  def create
    song = Song.new(song_params.merge(music_album_id: @album.id))
    flash.now[:notice] = "Successfully Created Song" if song.save
    flash.now[:error] = song.errors.full_messages.uniq.join(', ') if !song.save
    redirect_to music_album_songs_path(music_album_id: @album.id)
  end
  
  def edit
  end
  
  def update
    update_song = @song.update_attributes(song_params)
    flash.now[:notice] = "Successfully Updated Song" if update_song
    flash.now[:error] = @song.errors.full_messages.uniq.join(', ') if !update_song
    redirect_to music_album_songs_path(music_album_id: @album.id)
  end
  
  def destroy
    destroy_song = @song.delete
    flash.now[:notice] = "Successfully Deleted Song" if destroy_album
    flash.now[:error] = @song.errors.full_messages.uniq.join(', ') if !destroy_album
    redirect_to music_album_songs_path(music_album_id: @album.id)
  end
  
  private
  
  def song_params
    params.require(:song).permit(:song_attachment, :song_title, :duration)
  end
  
  def find_album
    @album = MusicAlbum.find_by_id(params[:music_album_id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/music_albums_helper.rb
module MusicAlbumsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/index.html.erb
<%if !@albums.blank?%>
	<div class="album-grid">
		<% @albums.each do |album|%>
			<div class="album-item">
				<%=link_to music_album_songs_path(music_album_id: album.id) do %>
					<div class="album-content">
						<div class="image"><%=image_tag album.photo_url(:thumb)%></div>
						<div class="name"><%=album.name%></div>	
					</div>
				<%end%>
			</div>
		<%end%>
	</div>
<%else%>
	<div class="noRecords"><span class="fa fa-info-circle"></span> No Albums Found</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumManagement</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home</title>
    <%= csrf_meta_tags %>
    
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
  	<header>
  		<div class="logo">
  			<span>
  				<%=link_to root_url do%>
  					<div>ToBee</div> 
  					<div><span class="fa fa-headphones"></span></div>
  				<%end%>
  			</span>
  		</div>
		<div class="navigation">
			<%if current_user%>
				<div class="nav">
					<%= link_to "Add Album", new_music_album_path%>
				</div>
			<%end%>
		</div>
  		<div class="search">
  			<div class="search-container">
  				<%= form_with url: root_path, class:"album_search_form", method: :get do |form| %>
  					<%= form.text_field "search_value", placeholder: "Search Song" %>
	  				<span class="submit"> 
	  					<%= link_to "", class:"album_search" do %>
	  						<span class="fa fa-search"></span>
	  					<%end%>
	  				</span>
	  			<%end%>
  			</div>
  		</div>
  		<div class="profile">
  			<%if current_user%>
	  			<div class="action">
	  				<%= current_user.email %>
	  			</div>
	  			<div class="action">
	  				<%= link_to "Logout", destroy_user_session_path, method: :delete%>
	  			</div>
  			<%else%>
	  			<div class="action">
		  			<%= link_to "Sign Up", new_user_registration_path%>
		  		</div>
		  		<div class="action">
		  			<%= link_to "Login", new_user_session_path%>
		  		</div>
  			<%end%>
  		</div>
  		
  	</header>
  	
  	<% if flash[:error]%>
	  	<div class="notification error">
	  		<div class="icon"><span class="fa fa-info-circle"></span></div>
	  		<div class="message"><%=flash[:error]%></div>
	  		<div class="close_notice"  onclick="$('.error').hide();"><span class="fa fa-times"></span></div>
	  	</div>
  	<%end%>
  	
  	<% if flash[:notice]%>
	  	<div class="notification success">
	  		<div class="icon"><span class="fa fa-check-circle"></span></div>
	  		<div class="message"><%=flash[:notice]%></div>
	  		<div class="close_notice" onclick="$('.success').hide();"><span class="fa fa-times"></span></div>
	  	</div>
  	<%end%>
  	
  	<div class="page-outer-contents">
		<div class="page-contents">
	    	<%= yield %>
	    </div>
	</div>
  </body>
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

</html>

app/views/music_albums/_form.html.erb
<div class="form-wrapper">
	<div class="page-form">
		<%= form_with model: @album do |form| %>
			<div class="row"><%= form.text_field :name, class: "form-control", placeholder: "Name" %></div>
			<div class="row"><%= form.text_field :genres, class: "form-control", placeholder: "Genres" %></div>
			<div class="row"><%= form.text_field :artist, class: "form-control", placeholder: "Director" %></div>
			<div class="row"><%= form.file_field :photo, class: "form-control", placeholder: "Upload photo" %></div>
			<div class="row"><%= form.submit "Submit", :class=>"btn btn-warning" %></div>
		<%end%>
	</div>
</div>

app/views/music_albums/edit.html.erb
<div class="breadcrumbs" style="background:#6f5b92;color:#FFF;">
	<span class="fa fa-home"></span> / Albums / <span class="active">Edit</span>
</div>
<div>
	<%= render "form"%>
</div>

app/views/music_albums/index.html.erb
<% if !@albums.blank? %>
	<% render @albums %>
<%else%>
	<%render "shared/insufficient_page"%>
<%end%>

app/views/music_albums/new.html.erb
<div class="breadcrumbs" style="background:#6f5b92;color:#FFF;">
	<span class="fa fa-home"></span> / Albums / <span class="active">New</span>
</div>
<div>
	<%= render "form"%>
</div>

app/views/music_albums/show.html.erb
<div>
	<div><%= image_tag(album.photo(:thumb)) %></div>
	<div><%= album.name %></div>
	<div><%= album.genres %></div>
	<div><%= album.artist %></div>
</div>

app/views/songs/_form.html.erb
<div class="form-wrapper">
	<div class="page-form">
		<%= form_with model: @song, url: music_album_songs_path(music_album_id: @album) do |form| %>
			<div class="row"><%= form.text_field :song_title, class: "form-control", placeholder: "Song Title" %></div>
			<div class="row"><%= form.text_field :duration, class: "form-control", placeholder: "Duration" %></div>
			<div class="row"><%= form.file_field :song_attachment, class: "form-control", placeholder: "Upload Song" %></div>
			<div class="row"><%= form.submit "Submit", :class=>"btn btn-warning" %></div>
		<%end%>
	</div>
</div>

app/views/songs/index.html.erb
<div class="song-index">
    <div class="top_sec">
      <div class="breadcrumbs">
			<span class="fa fa-home"></span> / Albums / <span class="active">New</span>
		</div>
      <div class="top_img_and_detail_div">
      	<div class="album-desc-section">
	         <span class="img_div">
	            <%=image_tag(@album.photo_url, class: "album_cover")%>
	         </span>
	         <span class="detail_div">
	            <span class="album_name"><%=@album.name%></span>
	            <span class="album_artist"><%= @album.artist %></span>
	         </span>
	         <span class="album-buttons-section">
		         <% if current_user %>
			         <%=link_to edit_music_album_path(@album) do%>
			         	<span class="btn btn-primary">Edit</span>
			         <%end%>
			         <%=link_to music_album_path(@album), method: :delete do%>
			         	<span class="btn btn-primary">Delete</span>
			         <%end%>
			         <%=link_to new_music_album_song_path(music_album_id: @album.id) do%>
			         	<span class="btn btn-primary">Add Song</span>
			         <%end%>
			     <%end%>
		     </span>
	     </div>
      </div>
    </div>
    <div class="bottom_sec">
        <span class="album_detail">
            <span class="album_details_heading">About This Album</span>    
            <span class="album_details_sub_heading">Artist</span>
            <span class="album_contents"><%= @album.artist %></span>
            <span class="album_details_sub_heading">Genres</span>
            <span class="album_contents"><%= @album.genres %></span>
        </span>
        <span class="other_album_detail">
           <%@songs.each do |song|%>
              <span class="songs_section"> 
                 <span class="songs_title">
                 	<span style="float:left;width: auto;"><%= song.song_title %></span>
                 	<span style="float:left;width: auto;padding-left: 10px;">
                 		<span class="fa fa-clock" style="padding-right: 3px;"></span>
                 		<%= song.duration %>
                 	</span>
                 </span>
                 <span class="songs_play">
                 	<audio controls>
					  <source src="<%=song.song_attachment%>" type="audio/mpeg">
					</audio>
                 </span>
              </span>
           <%end%>
        </span>
    </div>
</div>

app/views/songs/new.html.erb
<div class="breadcrumbs" style="background:#6f5b92;color:#FFF;">
	<span class="fa fa-home"></span> / Songs / <span class="active">New</span>
</div>
<div>
	<%= render "form"%>
</div>